### ISSUE TITLE
CLTS errors

### ISSUE THREAD

**Issue by FredericBlum** [SimonGreenhill/abvd_philippines#1]
@SimonGreenhill Thanks for transferring the repo!

We currently have 45 CLTS errors which we'd need to fix. Many of them are diacritics whose convention I am not familiar with in the Oceanic area. Mostly `^` and `ṣ` (syllabic?. There are also some cases in brackets, like the following:

| ID | LANGUAGE | CONCEPT | FORM | SEGMENTS |
|:--------------------------|-----------:|:--------------------|:---------------|:----------------------------------------------------------|
| 13-194_how-2 | 13 | 194_how | (k)abitáy | <s> <<(>> </s> k <s> <<)>> </s> a b i t á/a y/j |
| 13-207_twenty-1 | 13 | 207_twenty | duwá (ka) púlu | d u w á/a + <s> <<(>> </s> k a <s> <<)>> </s> + p ú/u l u |
| 13-208_fifty-1 | 13 | 208_fifty | líma (ka) púlu | l í/i m a + <s> <<(>> </s> k a <s> <<)>> </s> + p ú/u l u |

If you can give me some answers to those cases, I can try to implement the CLTS fixes myself.

**Comment by SimonGreenhill** [comment]
"(" and ")" can just be removed.  The ^ is probably a combining hat -- can you tell me what glyphs it's on?

**Comment by FredericBlum** [comment]
| 153-23_blood-1 | 153 | 23_blood | dugố | d u g <s> <<ố>> </s> |
| 202-107_wormearthworm-2 | 202 | 107_wormearthworm | b̂ab̂aŋoʔ | b <s> <<̂>> </s> a ɓ a ŋ o ʔ |
| 202-129_moon-1 | 202 | 129_moon | b̂oan | b <s> <<̂>> </s> o a n |
| 202-130_star-1 | 202 | 130_star | b̂intóhan | b <s> <<̂>> </s> i n t ó/o h a n |

There's also

| Segment | Freq |
--- | --- |
| <<ṵ>> | 3 |
| <<ⁱ>> | 5 | 
| <<ŭ>> | 18 | 
| <<ŝ>> | 33 | 
| <<ɦ>> | 33 |
| <<ʐ>> | 43 |

**Comment by SimonGreenhill** [comment]
/b^/ is probably a voiced bilabial implosive: ɓ
/ŝ/ is probably ʃ

**Comment by FredericBlum** [comment]
Ok, so the most frequent remaining cases are:

/ẓ/

/ṣ/

/ʐ/

/ḻ/

/ż/ 

Afterwards, I can focus on the individual ones, which are still hidden behind the cases above.

**Comment by FredericBlum** [comment]
@SimonGreenhill The message probably got lost, so pinging you again on this. After solving the five above, I can probably reduce the remaining errors quite a bit.

**Comment by SimonGreenhill** [comment]
Sorry, too many emails.

/ʐ/ is a voiced retroflex fricative
/ḻ/ change to /ð̞ /

These ones seem to be in Ferrell 69, so think they can just be removed:
/ṣ/ change to /s/
/ẓ/ change to /z/
/ż/ change to /z/
